---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: Z9z7WlwMPvQCMZE_euQBKHZq2rDCrCT_rCKzzx48LtUaoTYX1Y4yqRH87wt-4H_aNcS0azB1rkc2Z5WIuGl3zw==

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: Z9z7WlwMPvQCMZE_euQBKHZq2rDCrCT_rCKzzx48LtUaoTYX1Y4yqRH87wt-4H_aNcS0azB1rkc2Z5WIuGl3zw==

production:
  API_URL: <set to production API root>
  APP_URL: <set to production app URL>
  SESSION_SECRET: <use `rake generate:session_secret`>
